apiVersion: apps/v1
kind: Deployment
metadata:
  name: atb-heroes-dev-app-dep
  namespace: avanade-tech-and-beer
  labels:
    app: atb-heroes-dev
    tier: app
    version: v1
spec:
  selector:
    matchLabels:
      app: atb-heroes-dev
      tier: app
      version: v1
  replicas: 2
  template:
    metadata:
      labels:
        app: atb-heroes-dev
        tier: app
        version: v1
    spec:
      containers:
        - name: atbheroes
          image: 'technbeeracr1.azurecr.io/avengersheroes:latest'
          ports:
            - name: http 
              containerPort: 80
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 2
            periodSeconds: 3600
            httpGet:
              path: /swagger/index.html
              port: 80
          resources:
            requests:
              cpu: 25m
              memory: 150Mi                
 
