apiVersion: apps/v1
kind: Deployment
metadata:
  name: avaheroes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: techheroes
  template:
    metadata:
      labels:
        app: techheroes
    spec:
      containers:
      - name: techheroes
        image: technbeeracr1.azurecr.io/avengersheroes
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
